services:

  ai-service:
    build:
      context: ./ai-models/service
    ports:
      - "${AI_SERVICE_PORT:-8001}:8001"

  backend:
    build:
      context: ./app/backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      AI_SERVICE_URL: http://ai-service:8001
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - ai-service
      - mongodb

  frontend:
    build:
      context: ./app/frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend

  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
